[package]
name = "rsql"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt", "registry"] }

